### PR TITLE
Fix407

### LINKED ISSUE #407: generateDotGraph has re-entrance problem resulting in node ID conflict
I encounter a problem using gorgonia to generate the dot graph.

When I called twice in a same process (or go test to run different testing functions including dot.Marshal(g) in more than two places. The execution will produce
```
Error:
panic: simple: node ID collision: 3 [recovered]
	panic: simple: node ID collision: 3

goroutine 21 [running]:
testing.tRunner.func1.1(0x190dd20, 0xc00027e730)
	/usr/local/go/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc0000cde60)
	/usr/local/go/src/testing/testing.go:944 +0x3f9
panic(0x190dd20, 0xc00027e730)
	/usr/local/go/src/runtime/panic.go:967 +0x166
gonum.org/v1/gonum/graph/simple.(*DirectedGraph).AddNode(0xc000212e10, 0x1b1a180, 0xc0000a2d70)
	/Users/wzzhu/go/pkg/mod/gonum.org/v1/gonum@v0.0.0-20191009222026-5d5638e6749a/graph/simple/directed.go:49 +0x206
gorgonia.org/gorgonia/encoding/dot.generateDotGraph(0xc0000f9860, 0x16299b6, 0xc0000f5500, 0x1b2e580, 0xc000250b40)
	/Users/wzzhu/go/pkg/mod/gorgonia.org/gorgonia@v0.9.3/encoding/dot/topgraph.go:49 +0x320
```
The conflict ID is random.

I found probably it was due to the reentrance problem in generateDotGraph (topgraph.go). subGraph is a global variable having side effects in a same process.
```
var (
	subGraphs = map[internalEncoding.Group]subgrapher{
		internalEncoding.ConstantCluster: constantSubGraph{
			DirectedBuilder: simple.NewDirectedGraph(),
			name:            "Constants",
		},
		internalEncoding.InputCluster: inputSubGraph{
			DirectedBuilder: simple.NewDirectedGraph(),
			name:            "Inputs",
		},
		internalEncoding.ExprGraphCluster: exprSubGraph{
			DirectedBuilder: simple.NewDirectedGraph(),
			name:            "ExprGraph",
			subs:            make(map[internalEncoding.Group]operatorSubGraph),
		},
		internalEncoding.UndefinedCluster: exprSubGraph{
			DirectedBuilder: simple.NewDirectedGraph(),
			name:            "ExprGraph",
		},
	}
)

type attributer []encoding.Attribute

func (a attributer) Attributes() []encoding.Attribute { return a }

func generateDotGraph(g *gorgonia.ExprGraph) (graph.Graph, error) {
...
				if subgrapher, ok := subGraphs[group]; ok {
					subgrapher.(graph.DirectedBuilder).AddNode(n) 

```
A simple test snippets like this will reproduce it.
```
func TestDupDotCalls(t *testing.T) {
	g := gorgonia.NewGraph()
	var x, y, z *gorgonia.Node
	var err error

	// define the expression
	x = gorgonia.NewScalar(g, gorgonia.Float64, gorgonia.WithName("x"))
	y = gorgonia.NewScalar(g, gorgonia.Float64, gorgonia.WithName("y"))
	if z, err = gorgonia.Add(x, y); err != nil {
		t.Fatal(err)
	}
	b, err := dot.Marshal(g)
	if err != nil {
		glog.Errorf("Error printing graph: %v", err)
	}
	fmt.Printf("\n%s", string(b))

	var x2, y2, z2 *gorgonia.Node

	g2 := gorgonia.NewGraph()
	x2 = gorgonia.NewScalar(g2, gorgonia.Float64, gorgonia.WithName("x2"))
	y2 = gorgonia.NewScalar(g2, gorgonia.Float64, gorgonia.WithName("y2"))
	if z2, err = gorgonia.Add(x2, y2); err != nil {
		t.Fatal(err)
	}
	b2, err := dot.Marshal(g2)
	if err != nil {
		t.Errorf("Error printing graph: %v", err)
	}
	fmt.Printf("\n%s", string(b2))
	t.Logf("%v %v", z, z2)
}


```

### PR DESCRIPTION
**Pull request by chewxy**
Fixes #407

### CODE REVIEW

File: encoding/dot/topgraph.go [hunk 1]
```diff
@@ -9,8 +11,8 @@ import (
 	internalEncoding "gorgonia.org/gorgonia/internal/encoding"
 )
 
-var (
-	subGraphs = map[internalEncoding.Group]subgrapher{
```
Comment (owulveryck) [inline encoding/dot/topgraph.go:13]: All my life, i’ve been told that global variables are evil.... I am trying to convince myself that they are not. I guess my teacher were right :)
